version: '2.1'
services:
  ekar-mysql:
    container_name: ikc-mysql
    image: 'mysql/mysql-server:5.7'
    volumes:
      - ./dbdata:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ikcdb_001
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: '%'
    ports:
      - '3306:3306'
    restart: always
  smart-accounting-book-backend:
    image: smart-accounting-book-backend
    build:
      context: ./smart-accounting-book-backend
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    volumes:
      - /data/smart-accounting-book-backend
    depends_on:
      ekar-mysql:
        condition: service_healthy

