spring:
  # Database
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://ec2-44-198-151-32.compute-1.amazonaws.com:5432/d46qred6bk18hg
    username: ofxudxrveypiet
    password: dab3497a505ba904086d72e30aa037ce6028dad1e88177d2fad0eef549efc6dc
  # JPA properties
  jpa:
    hibernate:
      ddl-auto: update # When you launch the application for the first time - switch "none" at "create"
    show-sql: true
    #database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    #open-in-view: false
    generate-ddl: true