mysql:
  db_name: smartaccoutingbookdb

spring:
  datasource:
    url: jdbc:mysql://smartaccountingbookmysqlserver.mysql.database.azure.com:3306/${mysql.db_name}?createDatabaseIfNotExist=true
    username: sqladmin@smartaccountingbookmysqlserver
    password: SmartUser@123
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect