mysql:
  db_name: smartaccoutingbookdb

spring:
  datasource:
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://smartaccountingbookserver.database.windows.net:1433;database=smartaccoutingbookdb;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30; 
    #jdbc:sqlserver://smartaccountingbookserver.database.windows.net:1433;database=${mysql.db_name};
    username: sqladmin
    password: SmartUser@123
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
   # properties:
   #   hibernate:
   #     dialect: org.hibernate.dialect.SQLServer2012Dialect