email:
  sender:
    host: smtp.gmail.com
    port: 587
    username: niteen2010@gmail.com
    password: npqtjcwiswoiwnoe
  receiver:
    username: niteen.cg@gmail.com
  transport.protocol: smtp
  smtp:
    auth: true
    starttls:
      enable: true
  debug: false
  from:
    address: niteen2010@gmail.com