spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:test_mem1015;DB_CLOSE_DELAY=-1
    #url: jdbc:h2:file:${root.dir.path}/smart_accounting_book_db_266?createDatabaseIfNotExist=true;DB_CLOSE_DELAY=-1
    username: ENC(5kHwGk94fmuTxPlxV6hzNQ==)
    password:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect

      # naming:
      #   physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true
  sql:
    init:
      enabled: true

