##### Application path ########## Server port #####
server:
  port: 8080
#  servlet:
#    context-path: /api/

##### Profile Activation #####
spring:
  profiles:
    active:
      - mysql
    include:
      - mail
      #- log
      - jasper
      - validation

# App Properties
bezkoder:
  app:
    jwtSecret: bezKoderSecretKey
    jwtExpirationMs: 86400000

management:
  endpoints:
    web:
      exposure:
        include: '*'

#INSERT INTO roles(name) VALUES('ROLE_USER');
#INSERT INTO roles(name) VALUES('ROLE_MODERATOR');
#INSERT INTO roles(name) VALUES('ROLE_ADMIN');

