spring:
  datasource:
    url: jdbc:mysql://localhost:3306/rk_fert_090?createDatabaseIfNotExist=true
    username: root
    password: root@123
    platform: mysql
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
#    open-in-view: false