spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:test_mem
    initialization-mode: always
#   url: jdbc:h2:file:\${HOME}/Downloads/F_100;AUTO_SERVER=TRUE
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.dialect: org.hibernate.dialect.H2Dialect
      hibernate.format_sql: false
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  h2:
    console:
      enabled: true
      path: /h2-console