##### Application path ########## Server port #####
server:
  port: 8081
#servlet:
#context-path: /smart-accounting-book-backend

env:
  profile: prod

##### Profile Activation #####
spring:
  profiles:
    active:
      - mysql
    include:
      - mail
      #- log
      - jasper
      - validation

# App Properties
bezkoder:
  app:
    jwtSecret: bezKoderSecretKey
    jwtExpirationMs: 86400000

management:
  endpoints:
    web:
      exposure:
        include: '*'

#INSERT INTO roles(name) VALUES('ROLE_USER');
#INSERT INTO roles(name) VALUES('ROLE_MODERATOR');
#INSERT INTO roles(name) VALUES('ROLE_ADMIN');

jasypt:
  encryptor:
    password: Raj
    algorithm: PBEWithMD5AndDES
    iv-generator-classname: org.jasypt.iv.NoIvGenerator

#spring.devtools.restart.enabled: false

root:
  dir:
    path: D:\smart-accounting-book\database_back_up
    dump_exe_path: C:\Program Files\MySQL\MySQL Server 8.0\bin\mysqldump

