INSERT INTO roles
VALUES (1, 'ROLE_SUPER_ADMIN'),
       (2, 'ROLE_ADMIN'),
       (3, 'ROLE_USER');

INSERT INTO image
VALUES (1, '','favicon.ico','image/x-icon');

INSERT INTO bank_account
VALUES (1, 'ACCNOXXXXXXXXXX', 'HDFC', 'MG ROADXXXXXXX', 'MY SHOP XXXXXXXXX',
        'EMAIL@GMAIL.COM', 'GSTXXXXXXXXX', 'IFSCXXXXXXXXXX', 'PANNOXXXXXXX', '90365XXXXXXX', 1);
