spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dbname-ikc-007?createDatabaseIfNotExist=true
    username: root
    password: root@123
    platform: mysql
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect