spring:
  datasource:
    url: jdbc:mysql://mysql-docker-container:3306/dbname-ikc-005?createDatabaseIfNotExist=true
    username: root-user
    password: root@321
    platform: mysql
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect