spring:
  datasource:
    driverClassName: org.h2.Driver
    initialization-mode: always
    url: jdbc:h2:file:\${HOME}/Downloads/F_111;AUTO_SERVER=TRUE
         #jdbc:h2:file:/Users/niteenchougula/Downloads/F_110;AUTO_SERVER=TRUE
         #jdbc:h2:mem:test_mem006;DB_CLOSE_DELAY=-1
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.dialect: org.hibernate.dialect.H2Dialect
      hibernate.format_sql: false
     # naming:
     #   physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  h2:
    console:
      enabled: true
      path: /h2-console
