spring:
  datasource:
    url: jdbc:mysql://ikc-mysql:3306/ikcdb_001?createDatabaseIfNotExist=true
    username: root
    password: root
    platform: mysql
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    generate-ddl: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
#    open-in-view: false